const entries = [
  ['bed','Bed','Tempat tidur'],['pillow','Pillow','Bantal'],['blanket','Blanket','Selimut'],['sun','Sun','Matahari'],['window','Window','Jendela'],
  ['water','Water','Air'],['soap','Soap','Sabun'],['towel','Towel','Handuk'],['toothbrush','Toothbrush','Sikat gigi'],['toothpaste','Toothpaste','Pasta gigi'],
  ['shirt','Shirt','Baju'],['trousers','Trousers','Celana panjang'],['shoes','Shoes','Sepatu'],['socks','Socks','Kaus kaki'],['hat','Hat','Topi'],
  ['rice','Rice','Nasi'],['egg','Egg','Telur'],['banana','Banana','Pisang'],['milk','Milk','Susu'],
  ['bag','Bag','Tas'],['book','Book','Buku'],['pencil','Pencil','Pensil'],['chair','Chair','Kursi'],['school','School','Sekolah'],
  ['table','Table','Meja'],['teacher','Teacher','Guru'],['mosque','Mosque','Masjid'],['mat','Prayer mat','Sajadah'],['cap','Prayer cap','Peci'],
  ['ball','Ball','Bola'],['car','Toy car','Mobil mainan'],['doll','Doll','Boneka'],['blocks','Blocks','Balok mainan'],['kite','Kite','Layang-layang'],
  ['box','Box','Kotak'],['shelf','Shelf','Rak'],['basket','Basket','Keranjang'],['moon','Moon','Bulan'],['lamp','Lamp','Lampu'],
];
export const words = Object.fromEntries(entries.map(([id,en,idn]) => [id,{id,en,idn}]));
const request = (target, en, idn) => ({ target, en, idn });
export const activities = [
  {id:'wake',title:'Bangun tidur',en:'Good morning!',translation:'Selamat pagi!',icon:'sun',period:'Pagi ceria',words:['bed','pillow','blanket','sun','window'],phrases:[request('pillow','Where is my pillow?','Di mana bantalku?'),request('window','Open the window, please.','Tolong buka jendelanya.'),request('bed','Let’s make the bed.','Ayo rapikan tempat tidur.')],chat:['Good morning!','Good morning, Kiki!'],home:'Saat bangun, sapa bersama: “Good morning!”'},
  {id:'bath',title:'Mandi & sikat gigi',en:'Let’s get clean!',translation:'Ayo bersihkan diri!',icon:'soap',period:'Pagi ceria',words:['water','soap','towel','toothbrush','toothpaste'],phrases:[request('soap','Soap, please.','Tolong ambilkan sabun.'),request('towel','Where is my towel?','Di mana handukku?'),request('toothbrush','I need my toothbrush.','Aku perlu sikat gigiku.')],chat:['Let’s brush our teeth.','All right!'],home:'Tunjuk sabun dan handuk saat bersiap mandi, lalu sebut namanya bersama.'},
  {id:'dress',title:'Pakai baju',en:'Let’s get dressed!',translation:'Ayo berpakaian!',icon:'shirt',period:'Pagi ceria',words:['shirt','trousers','shoes','socks','hat'],phrases:[request('shoes','Put on your shoes.','Pakai sepatumu.'),request('shirt','This is my shirt.','Ini bajuku.'),request('hat','Where is my hat?','Di mana topiku?')],chat:['Are you ready?','I’m ready!'],home:'Saat memakai sepatu, coba ucapkan: “Put on your shoes.”'},
  {id:'eat',title:'Makan & minum',en:'I’m hungry!',translation:'Aku lapar!',icon:'banana',period:'Pagi ceria',words:['rice','egg','banana','milk','water'],phrases:[request('water','Water, please.','Tolong ambilkan air minum.'),request('banana','I want a banana.','Aku mau pisang.'),request('milk','I would like some milk.','Aku ingin susu.')],chat:['Here you are.','Thank you!'],home:'Bermain meminta minum dengan “Water, please”, lalu mengucapkan “Thank you”.'},
  {id:'school',title:'Pergi sekolah',en:'Let’s go to school!',translation:'Ayo pergi ke sekolah!',icon:'school',period:'Belajar & ibadah',words:['bag','book','pencil','chair','school'],phrases:[request('bag','This is my bag.','Ini tasku.'),request('book','Open your book, please.','Tolong buka bukumu.'),request('pencil','I need a pencil.','Aku perlu pensil.')],chat:['Hello!','Hello, teacher!'],home:'Siapkan tas bersama. Sebut book, pencil, dan bag sambil menunjuk bendanya.'},
  {id:'iqra',title:'Les & belajar Iqra',en:'Let’s learn together!',translation:'Ayo belajar bersama!',icon:'book',period:'Belajar & ibadah',words:['book','pencil','table','chair','teacher'],phrases:[request('book','Let’s read a book.','Ayo membaca buku.'),request('chair','Sit on the chair, please.','Silakan duduk di kursi.'),request('teacher','Let’s listen to the teacher.','Ayo dengarkan guru.')],chat:['May I ask a question?','Yes, of course.'],home:'Buka Iqra bersama pendamping dan cari huruf yang sudah dikenali. Latihan bacaan dilakukan bersama guru.'},
  {id:'pray',title:'Pergi salat',en:'Let’s go to the mosque.',translation:'Ayo pergi ke masjid.',icon:'mosque',period:'Belajar & ibadah',words:['mosque','mat','cap','water','shoes'],phrases:[request('mosque','Let’s go to the mosque.','Ayo pergi ke masjid.'),request('mat','Where is my prayer mat?','Di mana sajadahku?'),request('shoes','Take off your shoes, please.','Silakan lepas sepatumu.')],chat:['It’s time to pray.','Let’s go together.'],home:'Kenali masjid dan sajadah. Pendamping dapat mengajak bersiap salat sesuai kebiasaan keluarga.'},
  {id:'play',title:'Waktunya bermain',en:'Let’s play!',translation:'Ayo bermain!',icon:'ball',period:'Sore & malam',words:['ball','car','doll','blocks','kite'],phrases:[request('ball','Pass me the ball, please.','Tolong berikan bolanya kepadaku.'),request('kite','Let’s fly a kite.','Ayo bermain layang-layang.'),request('blocks','Let’s play with the blocks.','Ayo bermain balok.')],chat:['Can I play with you?','Yes, let’s play!'],home:'Bergantian memberikan bola sambil berkata: “Pass me the ball, please.”'},
  {id:'tidy',title:'Rapikan mainan',en:'Let’s tidy up!',translation:'Ayo bereskan!',icon:'box',period:'Sore & malam',words:['box','shelf','basket','ball','book'],phrases:[request('box','Put it in the box.','Masukkan ke dalam kotak.'),request('shelf','Put it on the shelf.','Letakkan di rak.'),request('basket','Bring me the basket, please.','Tolong bawakan keranjangnya.')],chat:['Can you help me?','Yes, I can!'],home:'Rapikan benda bersama. Tunjuk kotak saat mengatakan: “Put it in the box.”'},
  {id:'sleep',title:'Bersiap tidur',en:'I’m sleepy.',translation:'Aku mengantuk.',icon:'moon',period:'Sore & malam',words:['bed','pillow','blanket','moon','lamp'],phrases:[request('blanket','My blanket, please.','Tolong ambilkan selimutku.'),request('lamp','Turn off the lamp, please.','Tolong matikan lampunya.'),request('bed','Let’s go to bed.','Ayo tidur.')],chat:['Good night!','Good night. Sleep well!'],home:'Sebelum tidur, saling mengucapkan “Good night!” bersama keluarga.'},
];
export const getActivity = id => activities.find(a => a.id === id) || activities[0];
export const letters = [
  ['ا','Alif'],['ب','Ba'],['ت','Ta'],['ث','Tsa'],['ج','Jim'],['ح','Ha (ح)'],['خ','Kha'],['د','Dal'],
  ['ذ','Dzal'],['ر','Ra'],['ز','Zai'],['س','Sin'],['ش','Syin'],['ص','Shad'],['ض','Dhad'],['ط','Tha'],
  ['ظ','Zha'],['ع','Ain'],['غ','Ghain'],['ف','Fa'],['ق','Qaf'],['ك','Kaf'],['ل','Lam'],['م','Mim'],
  ['ن','Nun'],['ه','Ha (ه)'],['و','Wau'],['ي','Ya'],
].map(([glyph,name],i) => ({ id:`letter-${i}`,glyph,name }));
export const letterGroups = Array.from({length:7},(_,i) => letters.slice(i*4,i*4+4));
