import { activities, getActivity, words, letters, letterGroups } from './data.js';
import { createSession, createLettersSession, currentRound, choose, nextRound } from './engine.js';
import { feedbackFor } from './feedback.js';
import { loadSettings, saveSettings } from '../../shared/settings.js';
import { createSpeech } from '../../shared/speech.js';
import bunny from '../../assets/bunny.svg';
import banana from '../../assets/banana.svg';
import egg from '../../assets/egg.svg';
const assets=import.meta.glob('./assets/*.svg',{eager:true,query:'?url',import:'default'});
const imageFor=id=>id==='banana'?banana:id==='egg'?egg:assets[`./assets/${id}.svg`];
const picture=(id,alt=words[id]?.idn||'')=>`<img src="${imageFor(id)}" alt="${alt}" width="200" height="180" draggable="false">`;
const glyph=l=>`<span class="day-glyph" lang="ar" dir="rtl">${l.glyph}</span>`;
const letterById=id=>letters.find(l=>l.id===id);
const chatTranslations={wake:['Selamat pagi!','Selamat pagi, Kiki!'],bath:['Ayo sikat gigi.','Baik!'],dress:['Sudah siap?','Aku siap!'],eat:['Ini untukmu.','Terima kasih!'],school:['Halo!','Halo, Bu/Pak Guru!'],iqra:['Boleh aku bertanya?','Ya, tentu saja.'],pray:['Sudah waktunya salat.','Ayo pergi bersama.'],play:['Boleh aku ikut bermain?','Ya, ayo bermain!'],tidy:['Bisa bantu aku?','Ya, bisa!'],sleep:['Selamat malam!','Selamat malam. Tidur yang nyenyak!']};

export function mountDay(root,{hubUrl='/member/games/'}={}) {
  const settings=loadSettings(),events=new AbortController();
  let screen='map',activity=activities[0],session,feedback='',notice='',help=false,group=0;
  const speech=createSpeech(message=>{
    notice=message;const el=root.querySelector('#day-audio');if(el)el.textContent=message;
    if(message){help=true;root.querySelector('.day-prompt-picture')?.removeAttribute('hidden');}
  },{lang:'en-GB',languageName:'Inggris'});
  const speak=text=>{if(settings.sound)speech.say(text);};
  function listen(text){settings.sound=true;saveSettings(settings);syncSound();speech.say(text);}
  function syncSound(){const b=root.querySelector('[data-day="sound"]');b.textContent=`♫ Suara ${settings.sound?'nyala':'mati'}`;b.setAttribute('aria-pressed',String(settings.sound));}
  function changeScreen(next){speech.stop();screen=next;feedback='';notice='';help=false;render('h1');}
  function start(mode='words'){
    speech.stop();session=mode==='letters'?createLettersSession(letterGroups[group]):createSession(activity,mode);
    screen='play';feedback='';notice='';help=false;render('h1');if(mode!=='letters')speak(prompt().en);
  }
  function prompt(){const r=currentRound(session);return session.mode==='phrases'?r:{en:`Find the ${words[r.target]?.en.toLowerCase()}.`,idn:`Cari ${words[r.target]?.idn.toLowerCase()}.`};}
  const soundButton=(text,label='Dengarkan')=>`<button class="day-quiet" data-day="speak" data-text="${text}">♫ ${label}</button>`;
  function header(){return `<header class="day-header"><a class="day-brand" href="${hubUrl}"><span aria-hidden="true">❧</span> AnakHebat</a><button class="day-quiet" data-day="sound" aria-pressed="${settings.sound}">♫ Suara ${settings.sound?'nyala':'mati'}</button></header><nav class="day-nav"><a href="${hubUrl}">← Semua permainan</a><span>Sehari bersama Kiki</span></nav>`;}
  function map(){return `<section class="day-hero"><div><p class="day-eyebrow">PETUALANGAN 04 · ENGLISH SEHARI-HARI</p><h1>Hari kecil,<br><em>banyak kata baru.</em></h1><p class="day-lead">Temani Kiki dari pagi sampai malam.<br>Dengar, ketuk, lalu coba ucapkan!</p><button class="day-primary" data-day="begin">Mulai dari pagi <span aria-hidden="true">→</span></button><p class="day-caption">Mulai mudah · lima kata · dua pilihan</p></div><div class="day-hero-art" aria-hidden="true"><span class="day-hello" lang="en">Hello, friend!</span><span class="day-orbit day-sun">${picture('sun')}</span><img class="day-kiki" src="${bunny}" alt=""><span class="day-orbit day-moon">${picture('moon')}</span><span class="day-orbit day-book">${picture('book')}</span><span class="day-art-note">A little English, every day.</span></div></section><section class="day-map"><div class="day-section-head"><div><p class="day-eyebrow">MAU KE MANA HARI INI?</p><h2>Pilih kegiatanmu</h2></div><p>Boleh mulai dari mana saja.</p></div>${['Pagi ceria','Belajar & ibadah','Sore & malam'].map(period=>`<section class="day-period"><h3>${period}</h3><div class="day-activities">${activities.filter(a=>a.period===period).map(a=>`<button class="day-activity" data-day="activity" data-id="${a.id}">${picture(a.icon)}<span><strong>${a.title}</strong><small lang="en">${a.en}</small><b>5 kata · 3 kalimat ${a.id==='iqra'?'· + hijaiyah':''}</b></span><i aria-hidden="true">↗</i></button>`).join('')}</div></section>`).join('')}</section><aside class="day-kind"><span aria-hidden="true">♡</span><p>Tidak harus langsung bisa. Dengarkan lagi, coba lagi.<br><small>Boleh menirukan bersama pendamping, tanpa merekam suara.</small></p></aside>`;}
  function toolbar(label){return `<div class="day-toolbar"><button data-day="map">← Pilih kegiatan</button><span>${label}</span>${screen==='play'?'<button data-day="restart">↻ Mulai ulang</button>':''}</div>`;}
  function learn(){return `${toolbar('Kenalan kata')}<section class="day-learn"><div class="day-heading"><p class="day-eyebrow">${activity.title} · KENALAN DULU</p><h1 lang="en">${activity.en}</h1><p>${activity.translation}</p>${soundButton(activity.en,'Dengarkan sapaan')}</div><p class="day-instruction">Ketuk gambar untuk mendengar kata bahasa Inggrisnya.</p><div class="day-vocab">${activity.words.map(id=>`<button data-day="speak" data-text="${words[id].en}" class="day-word" aria-label="Dengarkan ${words[id].en}">${picture(id)}<strong lang="en">${words[id].en}</strong><span>${words[id].idn}</span><small>♫ Ketuk & dengar</small></button>`).join('')}</div><div class="day-learn-actions"><button class="day-primary" data-day="words">Ayo cari katanya <span aria-hidden="true">→</span></button><button class="day-secondary" data-day="phrases">Coba kalimat</button></div><p class="day-caption">Mulai dari dua gambar. Tidak perlu membaca sendiri.</p><details class="day-phrase-bank"><summary>Kenalan dengan kalimatnya <span aria-hidden="true">＋</span></summary><div>${activity.phrases.map(p=>`<article><p lang="en">${p.en}</p><small>${p.idn}</small>${soundButton(p.en)}</article>`).join('')}</div></details>${activity.id==='iqra'?`<aside class="day-iqra"><div><p class="day-eyebrow">BELAJAR BERSAMA PENDAMPING</p><h2>Kenalan huruf hijaiyah</h2><p>Kenali bentuk huruf, empat setiap kali.</p><small>Bagian ini memakai huruf Arab, terpisah dari latihan English.</small></div><button class="day-secondary" data-day="letters">Lihat huruf →</button></aside>`:''}</section>`;}
  function lettersScreen(){return `${toolbar('Kenalan hijaiyah')}<section class="day-learn"><div class="day-heading"><p class="day-eyebrow">LES & IQRA · HURUF DASAR</p><h1>Kenalan huruf hijaiyah</h1><p>Lihat bentuk dan titiknya. Sebutkan bersama pendamping.</p></div><div class="day-letter-groups" aria-label="Kelompok huruf">${letterGroups.map((ls,i)=>`<button data-day="group" data-id="${i}" aria-pressed="${i===group}" aria-label="Kelompok ${i+1}"><b>${i+1}</b><span>${ls.map(glyph).join('')}</span></button>`).join('')}</div><div class="day-letter-cards">${letterGroups[group].map(l=>`<article>${glyph(l)}<strong>${l.name}</strong></article>`).join('')}</div><p class="day-letter-note">Ini nama huruf, bukan bunyi bacaan berharakat. Audio huruf Arab belum tersedia; baca bersama pendamping.</p><button class="day-primary day-centered" data-day="letter-play">Cari huruf yang sama <span aria-hidden="true">→</span></button><button class="day-text day-centered" data-day="learn">← Kembali ke kosakata les</button><details class="day-phrase-bank"><summary>Catatan untuk pendamping</summary><p>28 huruf dasar dalam bentuk terpisah. Belum mencakup harakat, huruf sambung, atau pelajaran Iqra lengkap. Pengenalan bacaan dan makhraj dilanjutkan bersama guru. Nama Latin hanya membantu pendamping mengenali huruf.</p></details></section>`;}
  function play(){
    const r=currentRound(session),isLetters=session.mode==='letters',answered=session.status==='answered';
    const show=help||session.mode!=='phrases'||!settings.sound||!speech.available();
    return `${toolbar(isLetters?'Cari bentuk':session.mode==='words'?'Cari kata · mulai mudah':'Coba kalimat')}<section class="day-play"><div class="day-progress" aria-label="${session.index+1} dari ${session.rounds.length}">${session.rounds.map((_,i)=>`<span class="${i===session.index?'current':i<session.index?'visited':''}">${i+1}</span>`).join('')}</div><div class="day-heading"><p class="day-eyebrow">${isLetters?'HIJAIYAH · KELOMPOK '+(group+1):activity.title}</p><h1>${isLetters?'Mana huruf yang sama?':'Bantu Kiki, yuk!'}</h1><p>${isLetters?'Lihat contoh, lalu ketuk bentuk yang sama.':'Dengarkan, lalu ketuk gambar yang cocok.'}</p></div><div class="day-request"><img class="day-request-kiki" src="${bunny}" alt="Kiki"><div><p class="day-request-label">${isLetters?'LIHAT HURUFNYA':'KIKI BERKATA'}</p>${isLetters?`<div class="day-letter-target">${glyph(letterById(r.target))}<strong>${letterById(r.target).name}</strong></div>`:`<h2 lang="en">${prompt().en}</h2><p>${prompt().idn}</p>${soundButton(prompt().en,'Dengarkan lagi')}<div class="day-prompt-picture" ${show?'':'hidden'}>${picture(r.target)}<span lang="en">${words[r.target].en}</span></div>`}</div></div><div class="day-choice-label"><h2>Pilih satu gambar${isLetters?' huruf':''}</h2>${!isLetters?'<button class="day-quiet" data-day="hint">✧ Lihat bantuan</button>':''}</div><div class="day-choices ${r.choices.length===3?'three':''}">${r.choices.map(id=>`<button class="day-choice ${session.selected===id?'selected':''}" data-day="choose" data-id="${id}" aria-label="Pilih ${isLetters?letterById(id).name:words[id].en}" ${answered?'disabled':''}>${isLetters?glyph(letterById(id)):picture(id)}<strong ${isLetters?'':'lang="en"'}>${isLetters?letterById(id).name:words[id].en}</strong>${isLetters?'':`<span>${words[id].idn}</span>`}${session.selected===id?`<small>${answered?'✓ Cocok!':'↻ Coba lagi'}</small>`:''}</button>`).join('')}</div><p id="day-feedback" class="day-feedback" role="status">${feedback||'Boleh mencoba pelan-pelan.'}</p>${answered?`<button class="day-primary day-centered" data-day="next">${session.index===session.rounds.length-1?'Selesai':'Lanjut'} <span aria-hidden="true">→</span></button>`:''}<button class="day-text day-centered" data-day="${isLetters?'letters':'learn'}">← ${isLetters?'Lihat huruf lagi':'Kenalan kata lagi'}</button></section>`;
  }
  function finish(){const isLetters=session.mode==='letters';return `<section class="day-finish"><div class="day-heading"><p class="day-eyebrow">${isLetters?'HIJAIYAH · KELOMPOK '+(group+1):activity.title}</p><span class="day-finish-star" aria-hidden="true">✧</span><h1>Terima kasih<br><em>sudah mencoba!</em></h1><p>${isLetters?'Kamu sudah mengamati empat bentuk huruf.':'Kamu sudah menemani Kiki belajar kata dan kalimat.'}</p></div><div class="day-collected">${(isLetters?letterGroups[group]:activity.words.map(id=>words[id])).map(item=>`<article>${isLetters?glyph(item):picture(item.id)}<span ${isLetters?'':'lang="en"'}>${isLetters?item.name:item.en}</span></article>`).join('')}</div>${isLetters?'<aside class="day-kind"><span aria-hidden="true">♡</span><p>Cari huruf ini di buku Iqra bersama pendamping.<br><small>Belajar baca sedikit demi sedikit, tanpa terburu-buru.</small></p></aside>':`<section class="day-dialogue"><p class="day-eyebrow">COBA UCAPKAN BERSAMA</p><h2>Percakapan kecil kita</h2><div>${activity.chat.map((line,i)=>`<article><small>${i===0?'Kiki berkata':'Kamu boleh menjawab'}</small><p lang="en">${line}</p><span>${chatTranslations[activity.id][i]}</span>${soundButton(line)}</article>`).join('')}</div><p class="day-caption">Boleh mendengarkan saja. Tidak perlu merekam.</p></section><aside class="day-kind"><span aria-hidden="true">♡</span><p>${activity.home}</p></aside>`}<div class="day-finish-actions">${isLetters?'<button class="day-primary" data-day="next-group">Kelompok berikutnya →</button>':session.mode==='words'?'<button class="day-primary" data-day="phrases">Yuk, coba kalimat →</button>':'<button class="day-primary" data-day="next-activity">Kegiatan berikutnya →</button>'}<button class="day-secondary" data-day="restart">Main lagi ↻</button><button class="day-text" data-day="map">← Pilih kegiatan lain</button></div><p class="day-caption">Permainan ini bukan penilaian perkembangan anak.</p></section>`;}
  function render(focus){root.innerHTML=`<div class="day-page">${header()}<main>${screen==='map'?map():screen==='learn'?learn():screen==='letters'?lettersScreen():screen==='play'?play():finish()}</main><p id="day-audio" class="day-audio" role="status">${notice}</p><footer class="day-footer"><span>Langkah kecil, tumbuh bersama.</span><span>Suara tersimpan di browser ini. Progres belum disimpan atau tersinkron.</span></footer></div>`;if(focus){const el=root.querySelector(focus);if(el){if(el.tagName==='H1')el.tabIndex=-1;el.focus({preventScroll:focus!=='h1'});}}}
  root.addEventListener('click',event=>{
    const b=event.target.closest('[data-day]');if(!b||b.disabled)return;const action=b.dataset.day,id=b.dataset.id;
    if(action==='sound'){speech.stop();settings.sound=!settings.sound;saveSettings(settings);notice='';if(screen==='play'&&!settings.sound)help=true;render('[data-day="sound"]');if(settings.sound)speak('Hello! Let’s learn together.');return;}
    if(action==='speak'){listen(b.dataset.text);return;}
    if(action==='map'){changeScreen('map');return;}
    if(action==='begin'||action==='activity'){activity=getActivity(action==='begin'?'wake':id);changeScreen('learn');return;}
    if(action==='learn'){changeScreen('learn');return;}
    if(action==='words'||action==='phrases'){start(action);return;}
    if(action==='letters'){activity=getActivity('iqra');changeScreen('letters');return;}
    if(action==='group'){group=Math.min(6,Math.max(0,Number(id)));render(`[data-day="group"][data-id="${group}"]`);return;}
    if(action==='letter-play'){start('letters');return;}
    if(action==='next-group'){group=(group+1)%letterGroups.length;changeScreen('letters');return;}
    if(action==='next-activity'){activity=activities[(activities.indexOf(activity)+1)%activities.length];changeScreen('learn');return;}
    if(action==='restart'){start(session.mode);return;}
    if(action==='hint'){help=true;feedback='Lihat gambarnya. Dengarkan lagi, lalu coba pilih.';render('[data-day="hint"]');speak(prompt().en);return;}
    if(action==='choose'){
      speech.stop();const result=choose(session,id);if(result.kind==='ignored')return;
      feedback=feedbackFor(session,result,id);if(result.kind==='retry')help=true;
      render(result.kind==='correct'?'[data-day="next"]':`[data-day="choose"][data-id="${id}"]`);
      if(session.mode!=='letters')speak(result.kind==='correct'?`Yes! ${words[id].en}.`: `Let’s try again. ${prompt().en}`);return;
    }
    if(action==='next'&&nextRound(session)){speech.stop();feedback='';help=false;notice='';if(session.status==='complete')screen='finish';render('h1');if(screen==='play'&&session.mode!=='letters')speak(prompt().en);}
  },{signal:events.signal});
  window.addEventListener('pagehide',()=>speech.stop(),{signal:events.signal});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)speech.stop();},{signal:events.signal});
  render();return()=>{speech.stop();events.abort();};
}
