import './styles.css';
import {levels,locations,missionNames,words} from './data.js';
import {createState,choose,next} from './engine.js';
import {createAudio} from './audio.js';
const drawings={meja:'<path d="M18 40h64v12H18zM24 52v30m52-30v30"/>',gula:'<path d="m30 35 25-10 22 14-25 12zM30 35v32l22 14V51m0 30 25-13V39"/>',durian:'<path d="m50 20 8 9 13-4 2 13 12 7-7 12 3 14-14 2-10 10-10-9-15 2-2-14-9-10 9-11 1-13 14 1z"/>',nangka:'<ellipse cx="50" cy="53" rx="23" ry="32"/><path d="M50 21 57 9M37 40h1m15 5h1m9 12h1m-23 8h1m13 7h1"/>'};
function picture(w){return drawings[w.id]?`<svg viewBox="0 0 100 100" aria-hidden="true"><g fill="#f2cd75" stroke="#315c4b" stroke-width="5" stroke-linecap="round" stroke-linejoin="round">${drawings[w.id]}</g></svg>`:`<span aria-hidden="true">${w.picture}</span>`;}
export function mount(root,{hubUrl}){
 let state=createState(),screen='start',help=false,quiet=false,effects=true,message='',done=false;
 const events=new AbortController();
 const audio=createAudio(text=>{const el=root.querySelector('#ds-audio');if(el)el.textContent=text;});
 const mission=()=>state.missions[state.index];
 const target=()=>mission()?.target;
 function prompt(){const m=mission();return [ 'Dengarkan bunyi. Pilih gambarnya.',`Dengar: ${m.target.label}. Cari satu teman dengan bunyi awal yang sama.`,`Dengar: ${m.target.label}. Pilih bunyi pertamanya.`,`Dengar baik-baik: ${m.target.label}. Pilih bunyi awalnya.`,`Cari ${m.answers.length} gambar dengan bunyi awal seperti ${m.target.label}.`][state.index];}
 function listen(){const m=mission();if(m.kind==='environment')void audio.play(m.target.id,'',{environment:true});else void audio.play(`word-${m.target.id}`,prompt());}
 function render(focus=true){
 const m=mission();
 root.innerHTML=`<div class="ds-page"><header class="ds-header"><a href="${hubUrl}">← Main & Belajar</a><button data-act="effects" aria-pressed="${effects}">Efek ${effects?'nyala':'mati'}</button></header><main class="ds-main"><div class="ds-top"><span>✦ ANAKHEBAT · KOTA CERIA</span><label><input type="checkbox" data-act="quiet" ${quiet?'checked':''}> Main dengan gambar</label></div>${screen==='start'?start():screen==='finish'?finish():play(m)}<p id="ds-audio" role="status">${quiet?'Mode gambar. Pendamping boleh mencontohkan bunyi.':'Audio huruf memakai contoh kata sampai rekaman fonem tersedia.'}</p><details class="ds-parent"><summary>Catatan pendamping</summary><p>Luangkan waktu mendengar, menirukan, dan mencari benda di rumah. Tidak perlu cepat atau menuntaskan semuanya. Ini permainan, bukan tes perkembangan.</p><p>Bunyi lingkungan masih tiruan elektronik, bukan rekaman asli. Bunyi letup seperti /b/ tidak dipanjangkan menjadi “bbbb”. Contoh kata dibaca suara Indonesia perangkat jika tersedia. Mode gambar tetap bisa dimainkan.</p></details></main></div>`;
 if(focus)root.querySelector('h1')?.focus();
 }
 function levelPicker(){return `<div class="ds-levels">${levels.map(l=>`<button data-act="level" data-id="${l.id}" aria-pressed="${state.level===l.id}"><strong>${l.name}</strong><small>${l.note}</small></button>`).join('')}</div>`;}
 function start(){return `<section class="ds-hero"><div><p class="ds-eyebrow">DENGAR · CARI · TEMUKAN</p><h1 tabindex="-1">Detektif Suara<span>Cari Bunyi Rahasia</span></h1><p>Bantu Bintang dan burung Bunyi menjelajahi Kota Ceria. Ada kejutan bunyi di setiap sudut!</p><button class="ds-primary" data-act="start">Mulai petualangan →</button></div><div class="ds-character" aria-label="Detektif Bintang dengan kaca pembesar bintang dan burung Bunyi"><span>🧒🏽</span><b>✦</b><i>🐦</i><small>Bintang & Bunyi</small></div></section><h2>Pilih langkah kecilmu</h2>${levelPicker()}<div class="ds-map">${locations.map((l,i)=>`<span><b>${['🌳','🍳','🌷','🚗','🧺'][i]}</b>${l}</span>`).join('')}</div><p>Lima misi kecil. Boleh berhenti setelah misi mana pun.</p>`;}
 function play(m){const aided=help||quiet||!audio.available()||state.attempts>=2;return `<div class="ds-progress" aria-label="Misi ${state.index+1} dari 5">${locations.map((l,i)=>`<span class="${i===state.index?'current':''}">${state.completedIds.includes(i)?'★':i+1}<small>${l}</small></span>`).join('')}</div><section class="ds-board"><p class="ds-eyebrow">${locations[state.index]} · MISI ${state.index+1}</p><h1 tabindex="-1">${missionNames[state.index]}</h1><p class="ds-instruction">${prompt()}</p><div class="ds-clue"><div class="ds-target">${m.kind==='environment'?(aided?picture(m.target):'<span aria-hidden="true">👂</span>'):picture(m.target)}<strong>${m.kind==='environment'?(aided?m.target.label:'Bunyi rahasia'):m.target.label}</strong></div><div><button class="ds-primary" data-act="listen">♫ Ulangi suara</button><button data-act="help">✧ Bantu aku</button>${aided?`<p class="ds-hint">${m.kind==='environment'?m.target.clue:`Petunjuk: ${m.target.label} mulai dengan /${m.sound}/. Cari tanda ✦ pada gambar teman bunyinya.`}</p>`:''}</div></div><div class="ds-choices">${m.choices.map(w=>{const selected=state.selected.includes(w.id),hint=aided&&m.answers.includes(w.id);return `<div class="ds-choice-wrap"><button class="ds-choice ${hint?'ds-hinted':''}" data-act="choose" data-id="${w.id}" aria-label="Pilih ${w.label}" aria-pressed="${selected}" ${selected||done?'disabled':''}>${picture(w)}<strong>${w.label}</strong>${w.example?`<small>seperti ${w.example}</small>`:''}<b>${selected?'✓ Ditemukan':hint?'✦ Petunjuk':''}</b></button>${w.example?`<button class="ds-word" data-act="sound" data-id="${w.id}" aria-label="Dengarkan bunyi ${w.id}">♫ Dengarkan</button>`:`<button class="ds-word" data-act="word" data-id="${w.id}" aria-label="Dengarkan ${w.label}">♫ Kata</button>`}</div>`;}).join('')}</div><p id="ds-feedback" role="status">${message||'Bunyi menemanimu. Yuk, coba satu pilihan.'}</p>${done?`<div class="ds-success">★ Satu lencana usaha ditemukan!<button class="ds-primary" data-act="next">${state.index===4?'Buka Peta Bunyi':'Ke misi berikutnya'} →</button><button data-act="finish">Cukup untuk hari ini</button></div>`:''}</section><details class="ds-change"><summary>Ubah tingkat atau pilih misi</summary>${levelPicker()}${missionNames.map((n,i)=>`<button data-act="mission" data-id="${i}">${i+1}. ${n}</button>`).join('')}</details><button data-act="finish">Istirahat & lihat peta</button>`;}
 function finish(){const sounds=[...new Set(state.completedIds.map(i=>state.missions[i].sound).filter(Boolean))];return `<section class="ds-finish"><p class="ds-eyebrow">SETIAP USAHA BERARTI</p><h1 tabindex="-1">Peta Bunyi Hari Ini</h1><p>Kamu sudah menyelesaikan ${state.completed} misi. Terima kasih sudah mendengar dan mencoba!</p><div class="ds-map">${locations.map((l,i)=>`<span><b>${state.completedIds.includes(i)?'★':'☆'}</b>${l}</span>`).join('')}</div><p>${sounds.length?`Bunyi yang kamu jelajahi: ${sounds.map(s=>`/${s}/`).join(', ')}.`:'Petualangan bisa dilanjutkan kapan kamu siap.'}</p><div class="ds-badges"><span>👂<br>Telinga Teliti</span><span>🔎<br>Pencari Bunyi</span><span>🌟<br>Detektif Hebat</span></div><p>Bersama orang tua, cari dua benda di rumah yang bunyi awalnya sama. Coba ucapkan bergantian!</p><button class="ds-primary" data-act="restart">Main Lagi</button><button data-act="home">Pilih Misi Baru</button><a href="${hubUrl}">Kembali ke Main & Belajar →</a></section>`;}
 root.addEventListener('click',e=>{const el=e.target.closest('[data-act]');if(!el)return;const {act,id}=el.dataset;
 if(act==='listen'){listen();return;}if(act==='word'){const w=mission().choices.find(w=>w.id===id);void audio.play(`word-${id}`,w.label);return;}if(act==='sound'){const w=mission().choices.find(w=>w.id===id);void audio.play(`phoneme-${id}`,`Dengarkan awal kata ${w.example}. ${w.example}.`,{phoneme:true});return;}
 audio.stop();
 if(act==='effects')effects=!effects;
 if(act==='quiet')quiet=el.checked;
 if(act==='start'||act==='restart'){state=createState(state.level);screen='play';help=false;done=false;message='';}
 if(act==='level'){state=createState(id);done=false;help=false;message='';}
 if(act==='home'){screen='start';}
 if(act==='mission'){state=createState(state.level);state.index=Number(id);screen='play';done=false;help=false;message='';}
 if(act==='help')help=true;
 if(act==='finish')screen='finish';
 if(act==='next'){next(state);done=false;help=false;message='';if(state.index===5)screen='finish';}
 if(act==='choose'){const result=choose(state,id);message=result==='retry'?'Yuk dengarkan sekali lagi. Petunjuknya ada di awal bunyi.':result==='found'?'Iya, satu teman bunyi ditemukan. Cari lagi, yuk!':'Iya, kamu menemukannya! Terima kasih sudah mencoba.';done=result==='complete';if(done&&effects&&!quiet)audio.effect();}
 render(act!=='choose'&&act!=='help');
 if((act==='start'||act==='restart'||act==='next')&&screen==='play'&&!quiet)listen();
 if(act==='choose'){root.querySelector(done?'[data-act=next]':'.ds-choice:not(:disabled)')?.focus();if(!quiet){const w=mission().choices.find(w=>w.id===id);if(w.example)void audio.play('phoneme-'+id,'Dengarkan awal kata '+w.example+'. '+w.example+'.',{phoneme:true});else if(!done)listen();}}
 },{signal:events.signal});
 const stop=()=>audio.stop();document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();},{signal:events.signal});window.addEventListener('pagehide',stop,{signal:events.signal});render(false);return()=>{events.abort();audio.dispose();};
}
