import './styles.css';
import {modes,islands} from './data.js';
import {createState,answer,next} from './engine.js';
import {createAudio} from './audio.js';
export function mount(root,{hubUrl}){let state=createState(),screen='start',help=false,message='';const audio=createAudio(t=>{const x=root.querySelector('#pk-audio');if(x)x.textContent=t;});
 const render=()=>{const m=state.missions[state.index];root.innerHTML=`<div class="pk-page"><header><a href="${hubUrl}">← Main & Belajar</a><span>⛵ Kapal Kiki</span></header><main>${screen==='start'?start():screen==='finish'?finish():play(m)}<p id="pk-audio" role="status">Audio akan muncul setelah kamu mengetuk tombol.</p><details><summary>Catatan pendamping</summary><p>Belajar suku kata melalui gambar, suara dan susunan batu. Ini permainan, bukan tes.</p></details></main></div>`;};
 const start=()=>`<section class="pk-hero"><div><p class="pk-eyebrow">DENGAR · SUSUN · BERJALAN</p><h1>Petualangan Suku Kata<span>Jembatan Kata Ceria</span></h1><p>Bantu Kapal Kiki menyusun batu kata agar bisa menyeberang ke lima pulau.</p><button class="pk-primary" data-a="start">Mulai petualangan →</button></div><div class="pk-ship">⛵<b>🪨</b><i>🌈</i></div></section><h2>Pilih langkah kecilmu</h2><div class="pk-modes">${modes.map(x=>`<button data-a="mode" data-id="${x.id}" aria-pressed="${state.mode===x.id}"><strong>${x.name}</strong><small>${x.note}</small></button>`).join('')}</div><div class="pk-islands">${islands.map((x,i)=>`<span><b>${['🏝️','🌲','⛰️','🌊','🏰'][i]}</b>${x}</span>`).join('')}</div><p>Lima misi kecil, boleh berhenti kapan saja.</p>`;
 const play=m=>{const clue=help||state.attempts>=2;let body='';if(m.type==='clap')body=`<div class="pk-word">${m.word.picture}<strong>${m.word.label}</strong><small>${m.word.syllables.join(' · ')}</small></div><button class="pk-big" data-a="clap">👏 Tepuk bersama <b>${state.claps}/${m.need}</b></button>`;if(m.type==='pair')body=`<div class="pk-word">${m.word.picture}<strong>${m.word.label}</strong></div><p>Pilih gambar yang suku katanya tepat.</p><div class="pk-choices">${m.choices.map(w=>`<button data-a="pick" data-id="${w.id}">${w.picture}<strong>${w.syllables.join(' + ')}</strong><small>${w.label}</small></button>`).join('')}</div>`;if(m.type==='bridge'||m.type==='treasure')body=`<div class="pk-word">${m.word.picture}<strong>${m.word.label}</strong><small>${m.word.syllables.join(' · ')}</small></div><p>Pilih batu berikutnya untuk membangun jembatan.</p><div class="pk-stones">${m.stones.map((s,i)=>`<button data-a="stone" data-value="${s}" ${i<state.selected.length?'disabled':''}>${s}</button>`).join('')}</div>${clue?`<p class="pk-hint">Mulai dari <b>${m.word.syllables[0]}</b>, lalu ikuti bunyinya.</p>`:''}`;if(m.type==='split')body=`<div class="pk-word">${m.word.picture}<strong>${m.word.label}</strong></div><p>Pilih cara memecah kata ini.</p><div class="pk-choices">${m.choices.map(x=>`<button data-a="split" data-value="${x}">🪨 <strong>${x}</strong></button>`).join('')}</div>`;return `<div class="pk-progress">${islands.map((x,i)=>`<span class="${i===state.index?'now':''}">${i<state.completed?'★':i+1}<small>${x}</small></span>`).join('')}</div><section class="pk-board"><p class="pk-eyebrow">${islands[state.index]} · MISI ${state.index+1}</p><h1>${['Tepuk Suku Kata','Pilih Pasangan Suku Kata','Susun Jembatan Kata','Pecah Kata Menjadi Batu','Peti Harta Kata'][state.index]}</h1><p>Dengarkan pelan-pelan, lalu coba.</p><button data-a="listen">♫ Ulangi kata</button>${body}<p id="pk-feedback">${message||'Batu kata siap. Yuk coba!'}</p>${state.completed>state.index?`<div class="pk-success">★ Jembatan bertambah! <button class="pk-primary" data-a="next">${state.index===4?'Lihat peta':'Pulau berikutnya'} →</button></div>`:''}</section><button data-a="help">✧ Bantu aku</button> <button data-a="finish">Istirahat</button>`;};
 const finish=()=>`<section class="pk-finish"><p class="pk-eyebrow">JEMBATAN SELESAI</p><h1>Petualangan hebat!</h1><p>Kamu membantu Kapal Kiki melewati ${state.completed} pulau. Setiap susunan adalah usaha yang berarti.</p><div class="pk-islands">${islands.map((x,i)=>`<span><b>${i<state.completed?'★':'☆'}</b>${x}</span>`).join('')}</div><div class="pk-badges"><span>👂<br>Pendengar Kata</span><span>🪨<br>Penyusun Jembatan</span><span>🌟<br>Penjelajah Suku Kata</span></div><p>Bersama orang tua, tepuk kata benda di rumah.</p><button class="pk-primary" data-a="restart">Main lagi</button><a href="${hubUrl}">Kembali ke Main & Belajar →</a></section>`;
 root.addEventListener('click',e=>{const el=e.target.closest('[data-a]');if(!el)return;const a=el.dataset.a;audio.stop();if(a==='mode'){state=createState(el.dataset.id);screen='start';}if(a==='start'||a==='restart'){state=createState(state.mode);screen='play';message='';help=false;audio.say(`Kita mulai. ${islands[0]} menunggu kita.`);}if(a==='listen'){audio.say(`Dengar kata ${state.missions[state.index].word.syllables.join('…')}. ${state.missions[state.index].word.label}.`);}if(a==='help')help=true;if(a==='finish')screen='finish';if(a==='next'){next(state);if(state.index===5)screen='finish';message='';help=false;}if(a==='clap'){const r=answer(state);message=r==='complete'?'Hebat! Kata ini punya bagian bunyi yang jelas.':`Tepuk lagi, yuk. Dengarkan: ${state.missions[state.index].word.syllables.join('…')}.`;if(r==='complete')help=false;}if(a==='pick'){const w=state.missions[state.index].choices.find(w=>w.id===el.dataset.id);const r=answer(state,w.id);message=r==='complete'?`${w.syllables.join(' dan ')} menjadi ${w.label}!`: 'Kita dengarkan pelan-pelan, ya.';}if(a==='split'){const r=answer(state,el.dataset.value);message=r==='complete'?`Hebat! ${state.missions[state.index].word.label} menjadi ${state.missions[state.index].word.syllables.join(' | ')}.`:'Coba dengarkan bagian katanya lagi.';}if(a==='stone'){const r=answer(state,el.dataset.value);message=r==='complete'?`Jembatan ${state.missions[state.index].word.label} selesai!`:'Coba mulai dari batu pertama.';}render();if(['clap','pick','split','stone'].includes(a)&&message)audio.say(message);});render();return()=>audio.stop();}


